### ISSUE TITLE
switch to using a ruby version manager

### ISSUE THREAD

**Issue by dougcole** [estately/vagrant-devbox#2]
What we have no works, but next time we upgrade ruby versions we'll need a way to run multiple versions of ruby.

I'm a big fan of chruby, so I'd advocate for that, but I'm willing to listen to other ideas.

**Comment by norman** [comment]
I've experimented with different Ruby versions by building a new VM. We don't change Ruby versions that often, perhaps that might be enough? Setting up a version manager is entirely doable, but it's a bit more effort than just installing packages like we do now.

**Comment by norman** [comment]
So I ran into problems yesterday because Brightbox updated their packages to Ruby 2.3.3 and kindly **deleted** their Ruby 2.3.1 packages. As much as I hate having to wait while Ruby compiles this seems worth it to make sure we can always have the exact version we need. Working on it now.
